function acc_init_xblock(blk, varargin)

defaults = {'n_bits', 72, 'bin_pt', 17};
n_bits = get_var('n_bits', 'defaults', defaults, varargin{:});
bin_pt = get_var('bin_pt', 'defaults', defaults, varargin{:});

%% inports
data = xInport('data');
rst = xInport('rst');

%% outports
acc = xOutport('acc');

%% diagram

% block: kurtosis_moment_calc/acc_init_xblock/AddSub
Mux_out1 = xSignal('Mux_out1');
AddSub_out1 = xSignal('AddSub_out1');
AddSub = xBlock(struct('source', 'AddSub', 'name', 'AddSub'), ...
                       struct('precision', 'User Defined', ...
                              'arith_type', 'Signed  (2''s comp)', ...
                              'n_bits', n_bits, ...
                              'bin_pt', bin_pt), ...
                       {data, Mux_out1}, ...
                       {AddSub_out1});

% block: kurtosis_moment_calc/acc_init_xblock/Constant
Constant_out1 = xSignal('Constant_out1');
Constant = xBlock(struct('source', 'Constant', 'name', 'Constant'), ...
                         struct('const', 0, ...
                                'n_bits', n_bits, ...
                                'bin_pt', bin_pt, ...
                                'explicit_period', 'on'), ...
                         {}, ...
                         {Constant_out1});

% block: kurtosis_moment_calc/acc_init_xblock/Mux
Register_out1 = xSignal('Register_out1');
Mux = xBlock(struct('source', 'Mux', 'name', 'Mux'), ...
                    [], ...
                    {rst, Register_out1, Constant_out1}, ...
                    {Mux_out1});

% block: kurtosis_moment_calc/acc_init_xblock/Register
Register = xBlock(struct('source', 'Register', 'name', 'Register'), ...
                         [], ...
                         {AddSub_out1}, ...
                         {Register_out1});

% extra outport assignment
xConnector(acc,Register_out1);

end
