function acc_rst_init_xblock(blk, varargin)
defaults = {'acc_len', 2^14, 'acc_latency', 3};
acc_len = get_var('acc_len', 'defaults', defaults, varargin{:});
acc_latency = get_var('acc_latency', 'defaults', defaults, varargin{:});

%% inports
sync = xInport('sync');

%% outports
acc_rst = xOutport('acc_rst');
sync_out = xOutport('sync_out');

%% diagram
% block: kurtosis_moment_calc/acc_rst_init_xblock/Constant5
Constant5_out1 = xSignal('Constant5_out1');
Constant5 = xBlock(struct('source', 'Constant', 'name', 'Constant5'), ...
    struct('const', acc_len-1, ...
    'arith_type', 'Unsigned', ...
    'n_bits', log2(acc_len)+1, ...
    'bin_pt', 0, ...
    'explicit_period', 'on'), ...
    {}, ...
    {Constant5_out1});

% block: kurtosis_moment_calc/acc_rst_init_xblock/Counter
Counter_out1 = xSignal('Counter_out1');
Counter = xBlock(struct('source', 'Counter', 'name', 'Counter'), ...
    struct('n_bits', log2(acc_len), ...
    'rst', 'on'), ...
    {sync}, ...
    {Counter_out1});

% block: kurtosis_moment_calc/acc_rst_init_xblock/Logical
sync_del_out1 = xSignal('sync_del_out1');
Logical = xBlock(struct('source', 'Logical', 'name', 'Logical'), ...
    struct('logical_function', 'OR'), ...
    {sync_del_out1, sync}, ...
    {acc_rst});

% block: kurtosis_moment_calc/acc_rst_init_xblock/Relational
Relational_out1 = xSignal('Relational_out1');
Relational = xBlock(struct('source', 'Relational', 'name', 'Relational'), ...
    [], ...
    {Counter_out1, Constant5_out1}, ...
    {Relational_out1});

% block: kurtosis_moment_calc/acc_rst_init_xblock/acc_del
acc_del = xBlock(struct('source', 'Delay', 'name', 'acc_del'), ...
    struct('latency', acc_latency-1), ...
    {Relational_out1}, ...
    {sync_out});

% block: kurtosis_moment_calc/acc_rst_init_xblock/sync_del
sync_del = xBlock(struct('source', 'Delay', 'name', 'sync_del'), ...
    [], ...
    {Relational_out1}, ...
    {sync_del_out1});
end