function acc_dsp48e_init_xblock(blk, varargin)
%% inports
x = xInport('x');
rst = xInport('rst');

%% outports
sum_x = xOutport('sum_x');

%% diagram

% block: untitled/acc_dsp48e_init_xblock/DSP48E_0
DSP48_AB_splitter1_out1 = xSignal();
DSP48_AB_splitter1_out2 = xSignal();
Reinterpret_out1 = xSignal();
Mux_out1 = xSignal();
% dsp48e_ctrl_init_xblock14_out2 = xSignal('dsp48e_ctrl_init_xblock14_out2');
% dsp48e_ctrl_init_xblock14_out3 = xSignal('dsp48e_ctrl_init_xblock14_out3');
% dsp48e_ctrl_init_xblock14_out4 = xSignal('dsp48e_ctrl_init_xblock14_out4');
% dsp48e_ctrl_init_xblock14_out1 = xSignal('dsp48e_ctrl_init_xblock14_out1');
opmode_0_rst_out1 = xSignal('opmode_0_rst_out1');
zero_out1 = xSignal('zero_out1');

% block: untitled/acc_dsp48e_init_xblock/zero
% zero = xBlock(struct('source', 'Constant', 'name', 'zero'), ...
%                      struct('const', 0, ...
%                             'n_bits', 48, ...
%                             'bin_pt', 0, ...
%                             'explicit_period', 'on'), ...
%                      {}, ...
%                      {zero_out1});
zero_out1 = const('zero', 0, fi_dtype(1, 48, 0));


[acc_opmode, alumode, carryin, carryinsel] = dsp48e_ctrl('ctrl0', '0101100', '0000', '0', '000');


xBlock(struct('source', @dsp48e_AB_splitter_init_xblock, 'name', 'AB_splitter0'), ...
    {}, {zero_out1}, {DSP48_AB_splitter1_out1, DSP48_AB_splitter1_out2});


% block: untitled/acc_dsp48e_init_xblock/Mux
Mux = xBlock(struct('source', 'Mux', 'name', 'Mux'), ...
                    [], ...
                    {rst, acc_opmode, opmode_0_rst_out1}, ...
                    {Mux_out1});

% block: untitled/acc_dsp48e_init_xblock/Reinterpret
Reinterpret = xBlock(struct('source', 'Reinterpret', 'name', 'Reinterpret'), ...
                            struct('force_arith_type', 'on', ...
                                   'arith_type', 'Signed  (2''s comp)', ...
                                   'force_bin_pt', 'on'), ...
                            {x}, ...
                            {Reinterpret_out1});

% block: untitled/acc_dsp48e_init_xblock/opmode_0_rst
opmode_0_rst = xBlock(struct('source', 'Constant', 'name', 'opmode_0_rst'), ...
                             struct('const', 12, ...
                                    'arith_type', 'Unsigned', ...
                                    'n_bits', 7, ...
                                    'bin_pt', 0, ...
                                    'explicit_period', 'on'), ...
                             {}, ...
                             {opmode_0_rst_out1});



% block: untitled/acc_dsp48e_init_xblock/DSP48_AB_splitter1

DSP48E_0 = xBlock(struct('source', 'DSP48E', 'name', 'DSP48E_0'), ...
                         struct('use_creg', 'on'), ...
                         {DSP48_AB_splitter1_out1, DSP48_AB_splitter1_out2, Reinterpret_out1, Mux_out1, alumode, carryin, carryinsel}, ...
                         {sum_x});
end

