function mat_input_data_cplx_init_xblock(blk, varargin)
defaults = {'var_name', 'var', ...
    'n_bits', 36, ...
    'bin_pt', 0, ...
    'quantization', 'Truncate', ...
    'overflow', 'Wrap', ...
    'arith_type', 'Signed  (2''s comp)', ...
    'numerical_type', 'Fixed-point', ...
};

var_name = get_var('var_name', 'defaults', defaults, varargin{:});
arith_type = get_var('arith_type', 'defaults', defaults, varargin{:});
n_bits = get_var('n_bits', 'defaults', defaults, varargin{:});
bin_pt = get_var('bin_pt', 'defaults', defaults, varargin{:});
quantization = get_var('quantization', 'defaults', defaults, varargin{:});
overflow = get_var('overflow', 'defaults', defaults, varargin{:});
numerical_type = get_var('numerical_type', 'defaults', defaults, varargin{:});

%% outports
out = xOutport(var_name);

%% diagram
from_workspace_output = xSignal();
xBlock( struct('source', 'simulink/Sources/From Workspace', 'name', 'workspace_var'), ...
    {'VariableName', var_name}, {}, {from_workspace_output});

real_sig = xSignal();
imag_sig = xSignal();
real_out = xSignal();
imag_out = xSignal();
xBlock(struct('source', 'simulink/Math Operations/Complex to Real-Imag', 'name', 'c_to_ri_simulink'), ...
    {}, {from_workspace_output}, {real_sig, imag_sig});

xBlock(struct('source', 'Gateway In', 'name', 'gateway_real'), ...
    struct('n_bits', n_bits, ...
    'arith_type', arith_type, ...
    'gui_display_data_type', numerical_type, ...
    'bin_pt', bin_pt, ...
    'quantization', quantization, ...
    'overflow', overflow), ...
    {real_sig}, ...
    {real_out});

xBlock(struct('source', 'Gateway In', 'name', 'gateway_imag'), ...
    struct('n_bits', n_bits, ...
    'arith_type', arith_type, ...
    'gui_display_data_type', numerical_type, ...
    'bin_pt', bin_pt, ...
    'quantization', quantization, ...
    'overflow', overflow), ...
    {imag_sig}, ...
    {imag_out});

% combine into casper complex type
xBlock(struct('source', 'ri_to_c_init_xblock', 'name', 'ri_to_c'), {}, {real_out, imag_out}, {out});


end