function mult_35x25_init_xblock(blk, varargin)
%% config
defaults = {};

%% inports
A = xInport('In1');
B = xInport('In2');

%% outports
AB = xOutport('Out1');

%% diagram
% reinterp_concat_1_out1 = xSignal();
% pipe_del3_out1         = xSignal();
Concat_out1            = xSignal();
% Convert1_out1          = xSignal();
B_lsb_sign_ext        = xSignal();
DSP48E_0_p          = xSignal();
DSP48E_0_acout          = xSignal();
DSP48E_0_pcout          = xSignal();
pipe_del2_out1         = xSignal();
DSP48E_1_p          = xSignal();
covnert_B_out1         = xSignal();
B_msb             = xSignal();
B_lsb            = xSignal();
prod_lsb            = xSignal();
prod_msb            = xSignal();
% reinterp_B_out1        = xSignal();
B_msb_sign_ext        = xSignal();
% reinterp_concat_0_out1 = xSignal();

[opmode0, alumode0, carryin0, carryinsel0] = dsp48e_ctrl('ctrl0', '0000101', '0000', '0', '000');
[opmode1, alumode1, carryin1, carryinsel1] = dsp48e_ctrl('ctrl1', '1010101', '0000', '0', '000');

reinterp_B_out1 = reinterp_int('reinterp_B', B);
A_sign_ext = trunc_and_wrap('Convert1', A, 30, 0);



% block: mult_35x25/mult_35x25_init_xblock/covnert_B
covnert_B_out1 = trunc_and_wrap('convert_B', reinterp_B_out1, 35, 0);
% covnert_B = xBlock(struct('source', 'Convert', 'name', 'covnert_B'), ...
%     struct('n_bits', 35, ...
%     'bin_pt', 0), ...
%     {reinterp_B_out1}, ...
%     {covnert_B_out1});

% block: mult_35x25/mult_35x25_init_xblock/Slice
Slice = xBlock(struct('source', 'Slice', 'name', 'Slice'), ...
    struct('nbits', 18, ...
    'mode', 'Lower Bit Location + Width', ...
    'bit0', 17), ...
    {covnert_B_out1}, ...
    {B_msb});

% block: mult_35x25/mult_35x25_init_xblock/Slice1
Slice1 = xBlock(struct('source', 'Slice', 'name', 'Slice1'), ...
    struct('nbits', 17, ...
    'mode', 'Lower Bit Location + Width'), ...
    {covnert_B_out1}, ...
    {B_lsb});

% block: mult_35x25/mult_35x25_init_xblock/Slice2
Slice2 = xBlock(struct('source', 'Slice', 'name', 'Slice2'), ...
    struct('nbits', 17, ...
    'mode', 'Lower Bit Location + Width'), ...
    {DSP48E_0_p}, ...
    {prod_lsb});

% block: mult_35x25/mult_35x25_init_xblock/Slice3
Slice3 = xBlock(struct('source', 'Slice', 'name', 'Slice3'), ...
    struct('nbits', 43, ...
    'mode', 'Lower Bit Location + Width'), ...
    {DSP48E_1_p}, ...
    {prod_msb});

% block: mult_35x25/mult_35x25_init_xblock/covnert_B1
covnert_B1 = xBlock(struct('source', 'Convert', 'name', 'covnert_B1'), ...
    struct('n_bits', 18, ...
    'bin_pt', 0), ...
    {B_msb}, ...
    {B_msb_sign_ext});

% block: mult_35x25/mult_35x25_init_xblock/covnert_B2
% covnert_B2 = xBlock(struct('source', 'Convert', 'name', 'covnert_B2'), ...
%     struct('n_bits', 18, ...
%     'bin_pt', 0), ...
%     {B_lsb}, ...
%     {B_lsb_sign_ext});

B_lsb_sign_ext = trunc_and_wrap('convert_B2', B_lsb, 18, 0);

% block: mult_35x25/mult_35x25_init_xblock/pipe_del2
pipe_del2 = xBlock(struct('source', 'Register', 'name', 'pipe_del2'), ...
    [], ...
    {B_msb_sign_ext}, ...
    {pipe_del2_out1});





% block: mult_35x25/mult_35x25_init_xblock/DSP48E_0
DSP48E_0 = xBlock(struct('source', 'DSP48E', 'name', 'DSP48E_0'), ...
    struct('use_acout', 'on', ...
    'use_pcout', 'on', ...
    'pipeline_a', '2', ...
    'pipeline_b', '2'), ...
    {A_sign_ext, B_lsb_sign_ext, opmode0, alumode0, carryin0, carryinsel0}, ...
    {DSP48E_0_p, DSP48E_0_acout, DSP48E_0_pcout});

% block: mult_35x25/mult_35x25_init_xblock/DSP48E_1
DSP48E_1 = xBlock(struct('source', 'DSP48E', 'name', 'DSP48E_1'), ...
    struct('use_a', 'Cascaded from ACIN Port', ...
    'use_pcin', 'on', ...
    'pipeline_a', '2', ...
    'pipeline_b', '2'), ...
    {DSP48E_0_acout, pipe_del2_out1, DSP48E_0_pcout, opmode1, alumode1, carryin1, carryinsel1}, ...
    {DSP48E_1_p});






reinterp_concat_0_out1 = reinterp_uint('reinterp_concat_0', prod_lsb);
pipe_del3_out1 = delay_srl('del2', reinterp_concat_0_out1, 1);
reinterp_concat_1_out1 = reinterp_uint('reinterp_concat_1', prod_msb);

% block: mult_35x25/mult_35x25_init_xblock/Concat
Concat = xBlock(struct('source', 'Concat', 'name', 'Concat'), ...
    [], ...
    {reinterp_concat_1_out1, pipe_del3_out1}, ...
    {Concat_out1});

% block: mult_35x25/mult_35x25_init_xblock/reinterp_concat_2
reinterp_concat_2 = xBlock(struct('source', 'Reinterpret', 'name', 'reinterp_concat_2'), ...
    struct('force_arith_type', 'on', ...
    'arith_type', 'Signed  (2''s comp)', ...
    'force_bin_pt', 'on'), ...
    {Concat_out1}, ...
    {AB});


