function mult_35x25_init_xblock(blk, varargin)
%% config
defaults = {};

%% inports
In1 = xInport('In1');
In2 = xInport('In2');

%% outports
Out1 = xOutport('Out1');

%% diagram
reinterp_concat_1_out1 = xSignal();
pipe_del3_out1         = xSignal();
Concat_out1            = xSignal();
Convert1_out1          = xSignal();
covnert_B2_out1        = xSignal();
% dsp48e_ctrl_out1       = xSignal();
% dsp48e_ctrl_out2       = xSignal();
% dsp48e_ctrl_out3       = xSignal();
% dsp48e_ctrl_out4       = xSignal();
DSP48E_0_out1          = xSignal();
DSP48E_0_out2          = xSignal();
DSP48E_0_out3          = xSignal();
pipe_del2_out1         = xSignal();
% opmode1      = xSignal();
% alumode1      = xSignal();
% carryin1      = xSignal();
% carryinsel1      = xSignal();
DSP48E_1_out1          = xSignal();
covnert_B_out1         = xSignal();
Slice_out1             = xSignal();
Slice1_out1            = xSignal();
Slice2_out1            = xSignal();
Slice3_out1            = xSignal();
reinterp_B_out1        = xSignal();
covnert_B1_out1        = xSignal();
reinterp_concat_0_out1 = xSignal();


% block: mult_35x25/mult_35x25_init_xblock/dsp48e_ctrl
% xBlock(struct('source', @dsp48e_ctrl_init_xblock, 'name', 'ctrl0'), ...
%     {[], 'opmode', '0000101', 'alumode', '0000', 'carryin', '0', 'carryinsel', '000', 'consolidate_ports', 0}, ...
%     {}, {dsp48e_ctrl_out1, dsp48e_ctrl_out2, dsp48e_ctrl_out3, dsp48e_ctrl_out4});
[opmode0, alumode0, carryin0, carryinsel0] = dsp48e_ctrl('ctrl0', '0000101', '0000', '0', '000');
[opmode1, alumode1, carryin1, carryinsel1] = dsp48e_ctrl('ctrl1', '1010101', '0000', '0', '000');

% xBlock(struct('source', @dsp48e_ctrl_init_xblock, 'name', 'ctrl1'), ...
%     {[], 'opmode', '1010101', 'alumode', '0000', 'carryin', '0', 'carryinsel', '000', 'consolidate_ports', 0}, ...
%     {}, {opmode1, alumode1, carryin1, carryinsel1});


% block: mult_35x25/mult_35x25_init_xblock/Concat
Concat = xBlock(struct('source', 'Concat', 'name', 'Concat'), ...
    [], ...
    {reinterp_concat_1_out1, pipe_del3_out1}, ...
    {Concat_out1});

% block: mult_35x25/mult_35x25_init_xblock/Convert1
Convert1 = xBlock(struct('source', 'Convert', 'name', 'Convert1'), ...
    struct('n_bits', 30, ...
    'bin_pt', 0), ...
    {In1}, ...
    {Convert1_out1});

% block: mult_35x25/mult_35x25_init_xblock/DSP48E_0
DSP48E_0 = xBlock(struct('source', 'DSP48E', 'name', 'DSP48E_0'), ...
    struct('use_acout', 'on', ...
    'use_pcout', 'on', ...
    'pipeline_a', '2', ...
    'pipeline_b', '2'), ...
    {Convert1_out1, covnert_B2_out1, opmode0, alumode0, carryin0, carryinsel0}, ...
    {DSP48E_0_out1, DSP48E_0_out2, DSP48E_0_out3});

% block: mult_35x25/mult_35x25_init_xblock/DSP48E_1
DSP48E_1 = xBlock(struct('source', 'DSP48E', 'name', 'DSP48E_1'), ...
    struct('use_a', 'Cascaded from ACIN Port', ...
    'use_pcin', 'on', ...
    'pipeline_a', '2', ...
    'pipeline_b', '2'), ...
    {DSP48E_0_out2, pipe_del2_out1, DSP48E_0_out3, opmode1, alumode1, carryin1, carryinsel1}, ...
    {DSP48E_1_out1});

% block: mult_35x25/mult_35x25_init_xblock/Slice
Slice = xBlock(struct('source', 'Slice', 'name', 'Slice'), ...
    struct('nbits', 18, ...
    'mode', 'Lower Bit Location + Width', ...
    'bit0', 17), ...
    {covnert_B_out1}, ...
    {Slice_out1});

% block: mult_35x25/mult_35x25_init_xblock/Slice1
Slice1 = xBlock(struct('source', 'Slice', 'name', 'Slice1'), ...
    struct('nbits', 17, ...
    'mode', 'Lower Bit Location + Width'), ...
    {covnert_B_out1}, ...
    {Slice1_out1});

% block: mult_35x25/mult_35x25_init_xblock/Slice2
Slice2 = xBlock(struct('source', 'Slice', 'name', 'Slice2'), ...
    struct('nbits', 17, ...
    'mode', 'Lower Bit Location + Width'), ...
    {DSP48E_0_out1}, ...
    {Slice2_out1});

% block: mult_35x25/mult_35x25_init_xblock/Slice3
Slice3 = xBlock(struct('source', 'Slice', 'name', 'Slice3'), ...
    struct('nbits', 43, ...
    'mode', 'Lower Bit Location + Width'), ...
    {DSP48E_1_out1}, ...
    {Slice3_out1});

% block: mult_35x25/mult_35x25_init_xblock/covnert_B
covnert_B = xBlock(struct('source', 'Convert', 'name', 'covnert_B'), ...
    struct('n_bits', 35, ...
    'bin_pt', 0), ...
    {reinterp_B_out1}, ...
    {covnert_B_out1});

% block: mult_35x25/mult_35x25_init_xblock/covnert_B1
covnert_B1 = xBlock(struct('source', 'Convert', 'name', 'covnert_B1'), ...
    struct('n_bits', 18, ...
    'bin_pt', 0), ...
    {Slice_out1}, ...
    {covnert_B1_out1});

% block: mult_35x25/mult_35x25_init_xblock/covnert_B2
covnert_B2 = xBlock(struct('source', 'Convert', 'name', 'covnert_B2'), ...
    struct('n_bits', 18, ...
    'bin_pt', 0), ...
    {Slice1_out1}, ...
    {covnert_B2_out1});

% block: mult_35x25/mult_35x25_init_xblock/pipe_del2
pipe_del2 = xBlock(struct('source', 'Register', 'name', 'pipe_del2'), ...
    [], ...
    {covnert_B1_out1}, ...
    {pipe_del2_out1});

% block: mult_35x25/mult_35x25_init_xblock/pipe_del3
pipe_del3 = xBlock(struct('source', 'Register', 'name', 'pipe_del3'), ...
    [], ...
    {reinterp_concat_0_out1}, ...
    {pipe_del3_out1});

% block: mult_35x25/mult_35x25_init_xblock/reinterp_B
reinterp_B = xBlock(struct('source', 'Reinterpret', 'name', 'reinterp_B'), ...
    struct('force_arith_type', 'on', ...
    'arith_type', 'Signed  (2''s comp)', ...
    'force_bin_pt', 'on'), ...
    {In2}, ...
    {reinterp_B_out1});

% block: mult_35x25/mult_35x25_init_xblock/reinterp_concat_0
reinterp_concat_0 = xBlock(struct('source', 'Reinterpret', 'name', 'reinterp_concat_0'), ...
    struct('force_arith_type', 'on', ...
    'force_bin_pt', 'on'), ...
    {Slice2_out1}, ...
    {reinterp_concat_0_out1});

% block: mult_35x25/mult_35x25_init_xblock/reinterp_concat_1
reinterp_concat_1 = xBlock(struct('source', 'Reinterpret', 'name', 'reinterp_concat_1'), ...
    struct('force_arith_type', 'on', ...
    'force_bin_pt', 'on'), ...
    {Slice3_out1}, ...
    {reinterp_concat_1_out1});

% block: mult_35x25/mult_35x25_init_xblock/reinterp_concat_2
reinterp_concat_2 = xBlock(struct('source', 'Reinterpret', 'name', 'reinterp_concat_2'), ...
    struct('force_arith_type', 'on', ...
    'arith_type', 'Signed  (2''s comp)', ...
    'force_bin_pt', 'on'), ...
    {Concat_out1}, ...
    {Out1});


